import JwtDecode from 'jwt-decode';
import { AUTH } from '../pages/dashboard/session/DASHBOARD-SESSION.CONSTANTS';

class EnvClass {
  hmsToken =
    'eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJkZW1vLWFkbWluQGV4YW1wbGUuY29tIiwibmJmIjoxNTc0MDU3NDc5LCJ1c2FnZSI6IkFQSV9BQ0NFU1MiLCJpc3MiOiI0YTJlZGUxNjczY2MiLCJuYW1lIjoiVk13YXJlIEFkbWluIiwicGVybXMiOlsiaW10Z3VhIiwiZGdjbyIsImF6dWdyZGwiLCJsY3RzIiwicmN2Z2Rkc3IiLCJnd2dyYSIsImd3Z3JkIiwiZGdjYyIsImd3Z3JnIiwiZWdyIiwidWdydWUiLCJvZ3VwciIsImNwZ3VvIiwibmd2YyIsImRzZ2RkdCIsImltdGd1cyIsInN3dnIiLCJsaWNzZ3IiLCJhenVncmRzIiwiaWdkcSIsImxpY3NndSIsImRnY3QiLCJpbXRndXYiLCJjcGdjbyIsIm9ncm8iLCJjcGdkIiwiZHNndWR0IiwiaW10Z2NzIiwiYXp1Z2Rtc2wiLCJpbXRnY3YiLCJkZ3J0IiwicmdoaW9hIiwiZGdybyIsImF6dWdydm4iLCJjcGdyIiwib2dyYyIsImNkdGNyIiwiZGhnciIsImRnZSIsImRndXQiLCJvZ3VhIiwibGdtdCIsIm9nZHIiLCJ1aWciLCJ1Z3NlIiwib2d1YyIsImRwZ2p1Iiwib2dkbCIsImRwZ2pyIiwiaW10Z2NhIiwib2d1bCIsImRwZ2pkIiwicmN2Z3JiIiwiZHBnamMiLCJpbXRnYWwiLCJvZ2RjIiwidWdydSIsInBnYWEiLCJzd2d1IiwicmN2Z3JyYyIsImltdGdyYSIsImNtc2dkciIsInRoZ3IiLCJhenVnbnN0YSIsImF6dWdybCIsImF6dWdybiIsIm9nY3IiLCJpbWdnbHNpIiwib2djbCIsInN3Z2QiLCJvZ3NrZCIsImltdGdydiIsInNwZ250Iiwic3dnciIsImltdGdydCIsImF6dWdydiIsImltdGdycyIsIm9nc2thIiwiZGd1YyIsImF6dWdyciIsIm5namQiLCJuZ2pjIiwiYXp1Z3VuciIsInVnZHVlIiwidWd1dSIsImltZ2Nkc3IiLCJkciIsImNncyIsInJjdmdkYiIsInVndWUiLCJ1Z2R1IiwidmdyYyIsImZzZ3VmIiwicmN2Z2Nkc3IiLCJhenVnd3NsIiwic2JncmQiLCJ1Z2N1IiwicmN2Z2NiIiwiZHNncnNzIiwidnIiLCJ2Z3VjIiwiZnNnY2YiLCJyZ2VvYSIsImF6dWd3ZHMiLCJkc2dmbnMiLCJyZ2h1bSIsImNna3MiLCJpbWdnZGRzciIsInZnY2MiLCJkZ3V0dWEiLCJkcGd2dSIsImZzZ2RmIiwibmdqciIsImRnaWMiLCJuZ2p1IiwiZ2xvYmFsLWRlbGV0ZS1vcmciLCJtcmZ0IiwicmdlY2VhIiwidnBnciIsImNiZ2ZzIiwib2djdWEiLCJzcGdjbiIsInJnZXNlYSIsIm9jcCIsInN3bnIiLCJ2cGd1IiwicmdhYSIsIm5nc25tIiwiYXp1Z3dtc2wiLCJyY3ZnbW50IiwicmdtY24iLCJpbWdnY2kiLCJmc2dyZiIsInNwZ2RuIiwiaW10Z3IiLCJyZ2VjZSIsImRnbXUiLCJuZ3V1cyIsImltdGd1Iiwic2JnaSIsImF6dWdybnIiLCJhenVnZ21zbCIsIm1nZnRhIiwiYXp1Z3JubSIsInNwZ3VuIiwiYXp1Z3Jtc2wiLCJyZ2hpbyIsImF6dWdyZHNrcyIsInJnZXNlIiwiZHBnc2QiLCJvZ21jIiwibWdzZSIsImRwZ3NiIiwicmd0aSIsImltZ2dyaSIsIm1ncmUiLCJoaWEiLCJzd2JyIiwiYXp1Z2RkcyIsInJnaG9tIiwiYXp1Z3JjIiwib2dlIiwibmdzc2giLCJkc2d1Iiwicmdob2EiLCJkc2dyIiwicmN2Z2RyYyIsIm5ncmQiLCJkaGdkbCIsIm9nciIsImF6dWduc3RvIiwicmd2byIsImd3Z3VhIiwicmdlZyIsInZtZ2RsIiwicmdlbyIsImd3Z3VnIiwicmN2Z2xiIiwiYXp1Z3JyZyIsImRnY3R1YSIsInJnbXNwbiIsImRzciIsIm5nYWF0IiwicmdobyIsIm5nZCIsIm5nYyIsIm5nZSIsIm5nY2wiLCJ2bWd1IiwiZGdydHVhIiwiaW1nZ2RpIiwidm1nciIsImd3Z2RhIiwicmN2Z2NyYyIsImRwZ251IiwiaW1nZ2xkc3IiLCJuZ3IiLCJnd2dkZyIsImRncmMiLCJyZ2VnYSIsIm9nc2tkYSIsIm5nY2QiLCJyZ3BsbSIsImNnY2EiLCJhenVncnNsIiwicmdwbGsiLCJzcGdybiIsInJjdmdsZHNyIiwiZ3dnY2EiLCJnd2djZyIsImF6dWduciIsImd3Z2NkIiwiY2R0Z3IiXSwiZXhwIjoxNTc0MDU5MzM5LCJpYXQiOjE1NzQwNTc1MzksImp0aSI6ImRhYjU5NDJhIn0.T4hQ2lSlf2m-stjr0lJ7JtwFtBEyO8K3LVaAzxXU7qary5O2j4QsVNI-9Meekcg4WMXUL_rVNiZGDDstDp6PyjXCo9CSeTnL94g5T7yWQp5BkPKQuOt1f_HWYoNiGAi-oI4Gtj0TW3zPshg-dAVmV9NWROjtLRhpbP-tvl8Zslvb-iv_ZLkKkiAcrCukc-bvQAG_zKNO-0NGmDV90IOfuUMqszeSZJFnEQdfYh8ov0Ewy1HAg0-r_c1fb142oFK1gLX3M0O0gLlZ1catUNLsq4_3L3pD1FuQU_p9MQ_wsuttf90vvCJJnkOnkVlONjhRULi2vr8VQCUOuDgMoz6fHA';
  get token() {
    return sessionStorage.getItem(AUTH.HYDRA_AUTH_TOKEN);
    // return this.hmsToken;
  }

  set token(token: any) {
    sessionStorage.setItem(AUTH.HYDRA_AUTH_TOKEN, token || '');
  }

  get decodedToken() {
    return this.token ? JwtDecode(this.token) : null;
  }
}

const EnvService = new EnvClass();
export default EnvService;
