import JwtDecode from 'jwt-decode';
import { AUTH } from '../pages/dashboard/session/DASHBOARD-SESSION.CONSTANTS';

class EnvClass {
  hmsToken =
    'eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJkZW1vLWFkbWluQGV4YW1wbGUuY29tIiwibmJmIjoxNTg0NTA3OTExLCJ1c2FnZSI6IkFQSV9BQ0NFU1MiLCJpc3MiOiI0NDkzNzJiYWE0NjUiLCJuYW1lIjoiVk13YXJlIEFkbWluIiwicGVybXMiOlsiaW10Z3VhIiwiZGdjbyIsImF6dWdyZGwiLCJsY3RzIiwicmN2Z2Rkc3IiLCJnd2dyYSIsImd3Z3JkIiwiZ3dncmMiLCJkZ2NjIiwiZ3dncmciLCJlZ3IiLCJ1Z3J1ZSIsIm9ndXByIiwiY3BndW8iLCJuZ3ZjIiwiZHNnZGR0IiwiaW10Z3VzIiwic3d2ciIsImxpY3NnciIsImF6dWdyZHMiLCJpZ2RxIiwibGljc2d1IiwiZGdjdCIsImltdGd1diIsImNwZ2NvIiwib2dybyIsImNwZ2QiLCJkc2d1ZHQiLCJpbXRnY3MiLCJhenVnZG1zbCIsImltdGdjdiIsImRncnQiLCJyZ2hpb2EiLCJkZ3JvIiwiYXp1Z3J2biIsImNwZ3IiLCJvZ3JjIiwiY2R0Y3IiLCJkaGdyIiwiZGdlIiwiZHBnZGRzIiwiZGd1dCIsIm9ndWEiLCJsZ210Iiwib2dkciIsInVpZyIsInVnc2UiLCJvZ3VjIiwiZHBnanUiLCJvZ2RsIiwiZHBnanIiLCJpbXRnY2EiLCJvZ3VsIiwiZHBnamQiLCJyY3ZncmIiLCJkcGdqYyIsImltdGdhbCIsIm9nZGMiLCJ1Z3J1IiwicGdhYSIsInN3Z3UiLCJyY3ZncnJjIiwiaW10Z3JhIiwiY21zZ2RyIiwidGhnciIsImF6dWduc3RhIiwiYXp1Z3JsIiwiYXp1Z3JuIiwib2djciIsImltZ2dsc2kiLCJvZ2NsIiwic3dnZCIsImltdGdydiIsInNwZ250Iiwic3dnciIsImltdGdydCIsImF6dWdydiIsImltdGdycyIsImRndWMiLCJhenVncnIiLCJuZ2pkIiwibmdqYyIsImF6dWd1bnIiLCJ1Z2R1ZSIsInVndXUiLCJpbWdjZHNyIiwiZHBnZWMiLCJkciIsImNncyIsImRwZ2VkIiwicmN2Z2RiIiwidWd1ZSIsInVnZHUiLCJ2Z3JjIiwiZnNndWYiLCJyY3ZnY2RzciIsImF6dWd3c2wiLCJzYmdyZCIsInVnY3UiLCJyY3ZnY2IiLCJkc2dyc3MiLCJ2ciIsInZndWMiLCJmc2djZiIsInJnZW9hIiwiYXp1Z3dkcyIsImhkZ3IiLCJkc2dmbnMiLCJyZ2h1bSIsImNna3MiLCJpbWdnZGRzciIsInZnY2MiLCJkZ3V0dWEiLCJkcGd2dSIsImZzZ2RmIiwibmdqciIsImRnaWMiLCJkcGd3ZHMiLCJuZ2p1IiwiZHBnZXIiLCJnbG9iYWwtZGVsZXRlLW9yZyIsIm1yZnQiLCJyZ2VjZWEiLCJ2cGdyIiwiY2JnZnMiLCJvZ2N1YSIsInNwZ2NuIiwicmdlc2VhIiwib2NwIiwic3duciIsInZwZ3UiLCJyZ2FhIiwibmdzbm0iLCJhenVnd21zbCIsInJjdmdtbnQiLCJyZ21jbiIsImltZ2djaSIsImZzZ3JmIiwic3BnZG4iLCJpbXRnciIsInJnZWNlIiwiZGdtdSIsIm5ndXVzIiwiaW10Z3UiLCJzYmdpIiwiYXp1Z3JuciIsImF6dWdnbXNsIiwibWdmdGEiLCJhenVncm5tIiwic3BndW4iLCJhenVncm1zbCIsInJnaGlvIiwiYXp1Z3Jkc2tzIiwicmdlc2UiLCJkcGdzZCIsIm9nbWMiLCJtZ3NlIiwiZHBnc2IiLCJyZ3RpIiwiaW1nZ3JpIiwibWdyZSIsImhpYSIsInN3YnIiLCJhenVnZGRzIiwicmdob20iLCJhenVncmMiLCJvZ2UiLCJuZ3NzaCIsImRzZ3UiLCJyZ2hvYSIsImRzZ3IiLCJyY3ZnZHJjIiwibmdyZCIsImRoZ2RsIiwib2dyIiwiYXp1Z25zdG8iLCJyZ3ZvIiwiZ3dndWEiLCJyZ2VnIiwiZ3dndWMiLCJ2bWdkbCIsInJnZW8iLCJnd2d1ZyIsInJjdmdsYiIsImF6dWdycmciLCJkcGdyZHMiLCJkZ2N0dWEiLCJyZ21zcG4iLCJkc3IiLCJuZ2FhdCIsInJnaG8iLCJuZ2QiLCJuZ2MiLCJuZ2UiLCJuZ2NsIiwidm1ndSIsImRncnR1YSIsImltZ2dkaSIsImd3Z2RjIiwidm1nciIsImd3Z2RhIiwicmN2Z2NyYyIsImRwZ251IiwiaW1nZ2xkc3IiLCJuZ3IiLCJnd2dkZyIsImRncmMiLCJyZ2VnYSIsImltZ2dndHQiLCJuZ2NkIiwicmdwbG0iLCJjZ2NhIiwiYXp1Z3JzbCIsInJncGxrIiwic3Bncm4iLCJyY3ZnbGRzciIsImd3Z2NjIiwiZ3dnY2EiLCJnd2djZyIsImF6dWdyY3IiLCJhenVnbnIiLCJnd2djZCIsImNkdGdyIl0sImV4cCI6MTU4NDUwOTc3MSwiaWF0IjoxNTg0NTA3OTcxLCJqdGkiOiIwYWMwNGYzNiJ9.V7ATCyraeskISv5woHhznNOTO4xAkscv5mjDAQDGkbc66zEYYZQJwz8d6xG28BPKOTweuQs_r0TsghcF-2Ysc1KqO3dC_qQTjNPxC6Op3ugDwkDGA_FvDNNYTeP88THi5zbVoHnGFL7FZLjV2b4N2d8FhQkYotioR_NbAEC2cF9hkFmDEfIEexyRyZDXqWNWVqpXOATBkMI5qtdH5Dl2VqJrb9TkfWmlva2VbK4el3WiBSGbSFvAtfRGKBwQwxKoGb2q1GUxyy6cEKnmQdq5kiESQlohhuLOA9Nu1_kC3MfUxopUKKJ_yxqkFPWa0fthDMBmQ1sA8iri6iE9AnsRNA';
  get token() {
    // return sessionStorage.getItem(AUTH.HYDRA_AUTH_TOKEN);
    return this.hmsToken;
  }

  set token(token: any) {
    sessionStorage.setItem(AUTH.HYDRA_AUTH_TOKEN, token || '');
  }

  get decodedToken() {
    return this.token ? JwtDecode(this.token) : null;
  }
}

const EnvService = new EnvClass();
export default EnvService;
